# In this notebook, we are going to cover the fundamentals of **TensorFlow** with **TensorFlow**

We're going to cover :- 
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & Numpy
- Using `@tf.function` (a way to speed up regular python functions)
- Using GPUs with TensorFlow
- Some Exercises!

## Introduction To Tensors

In [1]:
# import tensorflow
import tensorflow as tf

print(tf.__version__)


2.10.0


In [2]:
# creating tensors with tf.constant()

scalar = tf.constant(69)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=69>

In [3]:
# Check the number of dimensions of the tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([69, 420])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 69, 420])>

In [5]:
vector.ndim

1

In [7]:
# Create a matrix
matrix = tf.constant([[10, 7],
                    [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
matrix_2 = tf.constant([[10., 7.], 
                        [7., 10.], 
                        [6., 9.]], 
                        dtype=tf.float16)

matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 6.,  9.]], dtype=float16)>

In [10]:
matrix_2.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3], 
                    [4, 5, 6]], 
                    [[7, 8, 9], 
                    [10, 11, 12]], 
                    [[13, 14, 15], 
                    [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [12]:
tensor.ndim

3

### Creating Tensors with `tf.Variable`

In [16]:
# Creating the same tensor with tf.Variable()

tensor_1 = tf.Variable([10, 7])
tensor_2 = tf.constant([10, 7])

tensor_1, tensor_2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [17]:
# Trying to change one of the elements in the changeable tensor
tensor_1[0]
tensor_1[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [18]:
tensor_1[0].assign(7)

tensor_1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [20]:
# Trying to change a value in unchangable tensor
tensor_2[0]
tensor_2[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [21]:
tensor_2[0].assign(7)
tensor_2

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑 Note - Rarely in practice we will need to explicitly use `tf.constant` or `tf.Variable` as TensorFlow automatically takes care of it for us. However, if need be, always use `tf.constant` and change it later (if the need arises).

### Creating Random Tensors

Random tensors are tensors of some arbitrary size which contain some random numbers.

In [2]:
import tensorflow as tf

In [4]:
random1 = tf.random.Generator.from_seed(38) # setting seed for reproducibility
random1 = random1.normal(shape=(3, 2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.20386009,  0.562024  ],
       [-2.3001142 , -1.349454  ],
       [ 0.81485   ,  1.2790666 ]], dtype=float32)>

In [5]:
random2 = tf.random.Generator.from_seed(38)
random2 = random2.normal(shape=(3, 2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.20386009,  0.562024  ],
       [-2.3001142 , -1.349454  ],
       [ 0.81485   ,  1.2790666 ]], dtype=float32)>

In [6]:
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.20386009,  0.562024  ],
        [-2.3001142 , -1.349454  ],
        [ 0.81485   ,  1.2790666 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.20386009,  0.562024  ],
        [-2.3001142 , -1.349454  ],
        [ 0.81485   ,  1.2790666 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of random elements in the tensor

In [7]:
not_shuffled = tf.constant([[10, 7], [5, 6], [8, 9]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6],
       [ 8,  9]])>

In [8]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [10,  7],
       [ 5,  6]])>

### Other Ways To Make Tensors

In [9]:
tf.ones([10, 7]) # create a tensor of given dimensions filled with all ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [10]:
tf.zeros([4, 2]) # create a tensor of given dimensons filled with all zeros

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

#### Turning NumPy arrays into Tensors
- Main difference between `np` arrays and `tf` tensors is that tensors can be run on GPUs

In [12]:
import numpy as np

arr = np.arange(1, 25, dtype=np.int32)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [13]:
ts = tf.constant(arr)

ts

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [14]:
ts2 = tf.constant(arr, shape=(2, 3, 4))

ts2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [16]:
ts3 = tf.constant(arr, shape=(6, 2, 2))

ts3

<tf.Tensor: shape=(6, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24]]])>

### Getting Information From Tensors
The main attributes of a Tensor are :- 
- Shape
- Size
- Rank
- Axis or Dimension

In [18]:
# Creating a rank 4 tensor :- 

r4 = tf.zeros(shape=[2, 3, 4, 5])

r4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
r4.shape, tf.size(r4), r4.ndim

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>, 4)

In [25]:
print(f"The datatype of every element :- {r4.dtype}")
print(f"Number of dimensions (rank) :- {r4.ndim}")
print(f"Shape of tensor :- {r4.shape}")
print(f"Elements along the 0th axis :- {r4.shape[0]}")
print(f"Elements along the last axis :- {r4.shape[-1]}")
print(f"Total number of elements :- {tf.size(r4)}")

The datatype of every element :- <dtype: 'float32'>
Number of dimensions (rank) :- 4
Shape of tensor :- (2, 3, 4, 5)
Elements along the 0th axis :- 2
Elements along the last axis :- 5
Total number of elements :- 120


### Manipulating Tensors
Performing some basic operations on tensors like +, -, *, and /

In [26]:
ts = tf.constant([[1, 3], [4, 6]])
ts

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 6]])>

In [27]:
ts + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 8]])>

In [28]:
ts * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [ 8, 12]])>

In [31]:
tf.multiply(ts, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [ 8, 12]])>

In [29]:
ts - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  1],
       [ 2,  4]])>

In [30]:
ts / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1.5],
       [2. , 3. ]])>

### Matrix Multiplication In TensorFlow
One of the most common operations in Deep Learning is multiplying one matrix (tensor) with another matrix (tensor)

In [1]:
import tensorflow as tf

In [2]:
tensor = tf.constant([[10, 2], [4, 5]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  2],
       [ 4,  5]])>

In [3]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[108,  30],
       [ 60,  33]])>

In [4]:
# but
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,   4],
       [ 16,  25]])>

In [5]:
tensor @ tensor # the @ symbol in python is for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[108,  30],
       [ 60,  33]])>

In [8]:
# Creating a tensor of 3, 2
tensor2 = tf.constant([[1, 2], [3, 4], [5, 6]])

tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [6]:
# creating another tensor of same shape
tensor3 = tf.constant([[4, 5], [6, 2], [9, 1]])

tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 2],
       [9, 1]])>

In [9]:
# multiplying tensor of same shape :- 
tensor2 @ tensor3

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [10]:
tf.matmul(tensor2, tensor3)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [13]:
# changing the shape of one matrix
tensor2 = tf.reshape(tensor2, shape=(2, 3))

In [14]:
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [15]:
# Multiplying again 
tensor2 @ tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 43,  12],
       [100,  36]])>

In [16]:
tf.matmul(tensor2, tensor3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 43,  12],
       [100,  36]])>

### Changing the datatype of a Tensor

In [17]:
import tensorflow as tf

In [18]:
A = tf.constant([[1, 2], [3, 4]])
A.dtype

tf.int32

In [19]:
B = tf.constant([[1.2, 4.5], [4.2, 5.3]])
B.dtype

tf.float32

In [20]:
# Changing the dtype of B from float32 to float16
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [22]:
# Changing from int32 to float32
A = tf.cast(A, dtype=tf.float32)
A, A.dtype

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 tf.float32)

### Aggregating Tensors
Aggregating tensors is basically condensing bigger values to form smaller values.
- `tf.abs()` -> take all the negative values and turn them into positive values.
- `tf.reduce_min()` -> finds the minimum value in the tensor
- `tf.reduce_max()` -> finds the maximum value in thhe tensor
- `tf.reduce_mean()` -> finds the mean of all values in the tensor
- `tf.reduce_sum()` -> finds the sum of all values in the tensor
- `tensorflow_probability.stats.variance()` -> to find the variance of the tensor
- `tf.math.reduce_std()` -> finds the standard deviation of the tensor but the tensor dtype should be `tf.float32` or `tf.float64`
- `tf.math.reduce_variance()` -> another way to find the variance of the tensor bubt the tensor dtype should be `tf.float32` or `tf.float64`

In [26]:
import tensorflow as tf
import numpy as np

In [25]:
# Getting the absolute values
A = tf.constant([-7, -10])
A, tf.abs(A)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>)

In [28]:
# Creating a random tensor with values between 0 and 100 of size 50
tensor = tf.constant(np.random.randint(0, 100, size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([59, 67, 94, 22, 54, 50, 36, 96, 51, 88, 75, 60,  3, 60, 46,  6, 32,
       62, 95, 78,  6, 87, 21, 53, 50, 24, 17, 98, 30, 54, 81, 10, 93,  8,
       33, 76, 63,  4, 70, 15, 59, 50, 57, 16,  6, 58, 79, 40, 73, 51])>

In [30]:
# Finding the minimum value in the tensor
tf.reduce_min(tensor).numpy()

3

In [31]:
# Finding the maximum value in the tensor
tf.reduce_max(tensor).numpy()

98

In [32]:
# Finding the mean value of the tensor
tf.reduce_mean(tensor).numpy()

50

In [33]:
# Finding the sum of all elements in the tensor
tf.reduce_sum(tensor).numpy()

2516

In [36]:
import tensorflow_probability as tfp

tfp.stats.variance(tensor).numpy()

791

In [37]:
tf.math.reduce_std(tensor)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int32'>.

In [38]:
tf.math.reduce_std(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.130724>

In [39]:
tf.math.reduce_variance(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=791.3376>

### Finding the positional maximum and minimum of a tensor

In [40]:
import tensorflow as tf

In [43]:
tensor = tf.random.uniform([50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.17696285, 0.3506565 , 0.76004314, 0.7168753 , 0.6031736 ,
       0.8445654 , 0.2771803 , 0.31367874, 0.03108037, 0.59690416,
       0.0749315 , 0.85958767, 0.66283834, 0.40657556, 0.03392851,
       0.2406925 , 0.6052853 , 0.478271  , 0.0459348 , 0.4504031 ,
       0.02827239, 0.05710888, 0.9417114 , 0.05181241, 0.9118483 ,
       0.9161918 , 0.32144523, 0.0113548 , 0.64285135, 0.31199133,
       0.7546884 , 0.5262389 , 0.36805868, 0.48353922, 0.02028608,
       0.3835827 , 0.9598136 , 0.9060234 , 0.96821797, 0.17389035,
       0.61325586, 0.28873634, 0.7014239 , 0.6333327 , 0.48024738,
       0.4867078 , 0.8980614 , 0.11641061, 0.29701436, 0.8332932 ],
      dtype=float32)>

In [48]:
# Finding the positional maxiumum - a.k.a argmax
idx = tf.argmax(tensor)
print(f" Argmax :- {idx} \n number at Argmax :- {tensor[idx]} \n maximum number in tensor :- {tf.reduce_max(tensor)}")

 Argmax :- 38 
 number at Argmax :- 0.9682179689407349 
 maximum number in tensor :- 0.9682179689407349


In [49]:
# Finding the positional minimum - a.k.a argmin
idx = tf.argmin(tensor)
print(f" Argmin :- {idx} \n number at Argmin :- {tensor[idx]} \n minimum number in tensor :- {tf.reduce_min(tensor)}")

 Argmin :- 27 
 number at Argmin :- 0.011354804039001465 
 minimum number in tensor :- 0.011354804039001465


### Squeezing a tensor (removing all the single dimensions)

In [50]:
import tensorflow as tf

In [53]:
tensor = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 50))
tensor

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.38256848, 0.8217803 , 0.70394695, 0.05114031, 0.04101658,
          0.6078191 , 0.13237083, 0.5112889 , 0.17512012, 0.54451203,
          0.5734432 , 0.26592588, 0.12513173, 0.16826105, 0.556249  ,
          0.03755295, 0.04056811, 0.19562864, 0.25415814, 0.5492728 ,
          0.26056123, 0.88029957, 0.6493126 , 0.8716556 , 0.3527168 ,
          0.8629453 , 0.5407407 , 0.26230395, 0.04201531, 0.35623777,
          0.47382522, 0.8072238 , 0.04239905, 0.6206852 , 0.6885387 ,
          0.74129236, 0.74778533, 0.8131155 , 0.38066816, 0.58388174,
          0.25225556, 0.41497052, 0.5058948 , 0.9814137 , 0.45095313,
          0.17220616, 0.16712618, 0.7964026 , 0.3814447 , 0.48759937]]]],
      dtype=float32)>

In [54]:
tensor.shape

TensorShape([1, 1, 1, 50])

In [56]:
squeezed_tensor = tf.squeeze(tensor)

In [57]:
squeezed_tensor.shape

TensorShape([50])

In [58]:
tensor.shape, squeezed_tensor.shape

(TensorShape([1, 1, 1, 50]), TensorShape([50]))

### One-Hot Encoding Tensors

In [59]:
import tensorflow as tf

In [60]:
list1 = [0, 1, 2, 3] # maybbe for red, green, blue and purple
tf.one_hot(list1, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [62]:
tf.one_hot(list1, depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

### Tensors and NumPy


In [63]:
import numpy as np
import tensorflow as tf

In [64]:
# Creating an array fron np.array directly

arr = np.array([1, 2, 3, 4])
tensor = tf.constant(arr)

arr, tensor, type(arr), type(tensor)

(array([1, 2, 3, 4]),
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>,
 numpy.ndarray,
 tensorflow.python.framework.ops.EagerTensor)

In [65]:
# The default types will differ based on the base arguement
from_numpy = tf.constant(np.array([1.3, 6.3]))
from_tf = tf.constant([1.3, 6.3])

from_numpy.dtype, from_tf.dtype

(tf.float64, tf.float32)

In [66]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [67]:
tf.config.list_logical_devices()


[LogicalDevice(name='/device:CPU:0', device_type='CPU')]